### ISSUE TITLE
Make and Style the Footer

### ISSUE THREAD

**Issue by GauravGupta993** [ideathon-2023/team-22#7]
Make and Style the Footer and fix it at the bottom of page.

**Comment by GURMEHAR-PEC** [comment]
I am creating footer fixed at the bottom

**Comment by ItsPranavz** [comment]
Assign this one to @GURMEHAR-PEC currently this issue is unassigned.

**Comment by ItsPranavz** [comment]
@GauravGupta993 please close, I think associated PR already merged.
